services:
    frontend:
        container_name: frontend
        build:
            context: frontend
            args:
                UI_PORT: ${UI_PORT}
                UI_HOST: ${UI_HOST}
                API_PORT: ${API_PORT}
                API_HOST: ${API_HOST}
        environment:
            - UI_PORT=${UI_PORT}
            - UI_HOST=${UI_HOST}
            - API_PORT=${API_PORT}
            - API_HOST=${API_HOST}
        stdin_open: true
        tty: true
        networks:
            - pythia_network
        ports:
            - ${UI_PORT}:${UI_PORT}
        volumes:
            - ./frontend/src:/app/src
            - ./frontend/public:/app/public

    backend:
        container_name: backend
        build:
            context: backend
        environment:
            - API_PORT=${API_PORT}
        stdin_open: true
        tty: true
        networks:
            - pythia_network
        ports:
            - ${API_PORT}:${API_PORT}
        volumes:
            - ./backend:/app

networks:
    pythia_network:
        name: pythia_network
        driver: bridge
