services:
    pythia-frontend:
        container_name: pythia-frontend
        build:
            context: frontend
            args:
                REACT_APP_UI_PORT: ${UI_PORT}
        stdin_open: true
        tty: true
        networks:
            - pythia_network
        volumes:
            - ./frontend/src:/app/src
            - ./frontend/public:/app/public

    pythia-backend:
        container_name: pythia-backend
        build:
            context: backend
        environment:
            - API_PORT=${API_PORT}
        stdin_open: true
        tty: true
        networks:
            - pythia_network
        volumes:
            - ./backend:/app

    pythia-proxy:
        container_name: pythia-proxy
        build:
            context: proxy
        restart: always
        ports:
            - ${PYTHIA_PORT}:80
        environment:
            - UI_PORT=${UI_PORT}
            - API_PORT=${API_PORT}
        networks:
            - pythia_network
        healthcheck:
            test: ["CMD", "service", "nginx", "status"]
            interval: 10s
            timeout: 10s
            retries: 6
            start_period: 120s
        depends_on:
            pythia-frontend:
                condition: service_started
                restart: true
            pythia-backend:
                condition: service_started
                restart: true

networks:
    pythia_network:
        name: pythia_network
        driver: bridge
