services:
   pythia:
        container_name: pythia
        build:
            context: .
        environment:
            - UI_PORT=${UI_PORT}
            - UI_HOST=${UI_HOST}
        stdin_open: true
        tty: true
        ports:
            - ${UI_PORT}:${UI_PORT}
        volumes:
            - ./src:/app/src
            - ./public:/app/public